name: C/C++ CI

on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1000
      matrix:
          board: [nrf52dk_nrf52832, nrf52840dk_nrf52840, nrf54l15dk_nrf54l15_cpuapp, nrf54l15dk_nrf54l15_cpuapp_ns,nrf5340dk_nrf5340_cpuapp, nrf5340dk_nrf5340_cpuapp_ns, nrf7002dk_nrf5340_cpuapp, nrf7002dk_nrf5340_cpuapp_ns, nrf9151dk_nrf9151_ns, nrf9160dk_nrf9160, nrf9160dk_nrf9160_ns, nrf9161dk_nrf9161, nrf9161dk_nrf9161_ns, nrf52833dk_nrf52833, nrf52840dk_nrf52840 ]
          project: [l2/l2_e1_sol, l2/l2_e2_sol, l3/l3_e1_sol, l3/l3_e2_sol, l4/l4_e1_sol, l4/l4_e2_sol, l4/l4_e3_sol, l5/l5_e1_sol/, l6/l6_e1_sol/, l6/l6_e2_sol/, l7/l7_e1_sol, l7/l7_e2_sol, l7/l7_e3_sol, l8/l8_e1_sol/, l8/l8_e2_sol/ ]
          exclude:
            - board: nrf54l15dk_nrf54l15_cpuapp_ns, nrf54l15dk_nrf54l15_cpuapp, nrf7002dk_nrf5340_cpuapp_ns, nrf7002dk_nrf5340_cpuapp
            - project: l6/l6_e2_sol/
              
              
          
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: image pull
      run: docker pull nordicplayground/nrfconnect-sdk:v2.9-branch
    - name: build sample
      run: docker run  --rm -v ${PWD}:/workdir/project -w /workdir/project/v2.9.0-v2.7.0 nordicplayground/nrfconnect-sdk:v2.9-branch  west build ${{ matrix.project }} -b ${{ matrix.board }} --build-dir ${{ matrix.project }}/build
