name: C/C++ CI

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    container: nordicplayground/nrfconnect-sdk:v2.9-branch

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: cd v2.9.0-v2.7.0
    - name: build
      run: west build l6/l6_e1_sol/ -b nrf5340dk_nrf5340_cpuapp --build-dir build
      
 
