name: C/C++ CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: image pull
      run: docker pull nordicplayground/nrfconnect-sdk:v2.9-branch
    - name: build sample
      run: docker run  --rm -v ${PWD}:/workdir/project -w /workdir/project/v2.9.0-v2.7.0 nordicplayground/nrfconnect-sdk:v2.9-branch  west build l6/l6_e1_sol/ -b nrf5340dk_nrf5340_cpuapp --build-dir build
