name: C/C++ CI

on: [push]
jobs:
  build:
    strategy:
      max-parallel: 10
      matrix:
          board: [nrf52840dk_nrf52840, nrf5340dk_nrf5340_cpuapp]
          project: [l2/l2_e1_so1, l2/l2_e2_sol, l3/l3_e1_so1, l3/l3_e2_sol, l4/l4_e1_so1, l4/l4_e2_sol, l4/l4_e3_sol, l5/l5_e1_sol/, l6/l6_e1_sol/, l6/l6_e2_sol/, l7/l7_e1_so1, l7/l7_e2_sol, l7/l7_e3_sol, l8/l8_e1_sol/, l8/l8_e2_sol/ ]
            
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: image pull
      run: docker pull nordicplayground/nrfconnect-sdk:v2.9-branch
    - name: build sample
      run: docker run  --rm -v ${PWD}:/workdir/project -w /workdir/project/v2.9.0-v2.7.0 nordicplayground/nrfconnect-sdk:v2.9-branch  west build ${{ matrix.project }} -b ${{ matrix.board }} --build-dir ${{ matrix.project }}/build
