name: C/C++ CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: image pull
      run: docker pull nordicplayground/nrfconnect-sdk:v2.9-branch
    - name: build sample
      run: docker run  --rm -v ${PWD}:/workdir/project -w /workdir/project/v2.9.0-v2.7.0 nordicplayground/nrfconnect-sdk:v2.9-branch ls 

 
